                                        PROGRAMAÇÃO CIENTÍFICA
                                     
                                       ÁLGEBRA LINEAR COM PYTHON
                                       
                                 PROJETO DESENVOLVIDO POR THIAGO BARROS

Baseada na Bibliografia do Álgebra Linear - Alfredo Steinbruch e do Paulo Winterle

e utilizando o módulo de álgebra linear, [**Numpy**](https://numpy.org/doc/stable/index.html)

In [2]:
import numpy as np

1° - Parte - Matrizes

$$
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}
$$

**Matriz** é um conjunto bidimensional de elementos organizados em linhas e colunas. Uma Matriz porde conter
$m$ linhas e $n$ colunas.

Um elemento de uma matriz é definido com o posicionamento $a_{ij}$ onde o $i$ é a representação da linha que está
o elemento e $j$ é a coluna que o mesmo se encontra.


1.1 - Tipos de Matrizes

As matrizes são definidas da seguinte forma:

A) **Matriz retangular**  - $m$ e $n$ são diferentes ou seja, uma matriz que possui mais linhas do que colunas
ou o inverso.

Exemplo 1.1

$$
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}_{2x3}
$$

Exemplo 1.2

$$
\begin{bmatrix}
1 & 2 \\
4 & 5 \\
7 & 8
\end{bmatrix}_{3x2}
$$

In [ ]:
# Representação no Python - Utilizando o módulo numpy

In [9]:
exemplo1 = np.array([[1,2,3],[4,5,6]])
print(exemplo1)

[[1 2 3]
 [4 5 6]]


No módulo numpy, perceba que a matriz é representada como entre cochetes. No numpy, o tipo de dado é definido
como um **array**, e a matriz propriamente dita é um conjunto de arrays.

arranjo = np.array([MATRIZ])

Dentro de matriz as linhas são representads por entre cochetes também e separadas por vírgulas

[[linha 1],[linha 2],[linha 3], ...]

In [7]:
print(type(exemplo1))

<class 'numpy.ndarray'>


In [8]:
exemplo2 = np.array([[1,2],[4,5],[7,8]])
print(exemplo2)

[[1 2]
 [4 5]
 [7 8]]


B) **Matriz Linha e Coluna** - Como o nome já diz, são matrizes que um dos coeficientes de linha ou coluna é 1, ou seja, só existe
uma única dimensão

Exemplo 1.3

$$
\begin{bmatrix}
1\\
2\\
3\\
4\\
\vdots\\
a_{m 1}
\end{bmatrix}_{mx1}
$$

Exemplo 1.4

$$
\begin{bmatrix}
1 & 2 & 3 & \dots & a_{1n}
\end{bmatrix}_{1xn}
$$

In [11]:
exemplo3 = np.array([[1],[2],[3]])
print(exemplo3)

[[1]
 [2]
 [3]]


In [14]:
exemplo4 = np.array([1,2,3,4])
print(exemplo4)

[1 2 3 4]


Perceba que a matriz linha é similar a lista que é um formato padrão do Python. É possivel
converter uma lista no Python para um arranjo/matriz linha da seguinte forma:

In [15]:
lista = [1,2,3]
linha = np.array(lista)

O Módulo numpy interpreta como sendo um arranjo unidimensional e armazena no tipo
array.

In [17]:
print(linha)

[1 2 3]


B) **Matriz Quadrada** - São as matrizes que o número de linhas é igual ao de colunas ou seja,
$m = n$

Exemplo 1.5

$$
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
6 & 7 & 8
\end{bmatrix}_{3x3}
$$

In [18]:
exemplo5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(exemplo5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
